name: Build and publish C# app

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        runtime: [win-x64, win-x86]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Build and publish app
      run: dotnet publish -c Release -r ${{ matrix.runtime }} -o ${{env.DOTNET_ROOT}}/Il2CppDumper-${{ matrix.runtime }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Il2CppDumper-${{ matrix.runtime }}
        path: ${{env.DOTNET_ROOT}}/Il2CppDumper-${{ matrix.runtime }}
